version: '3.9'

services:
  api:
    build: .
    depends_on:
      - db
#    env_file:
#      - .env
    command: npm run start:dev
    ports:
      - '5000:5000'
  db:
    image: 'postgres'
    restart: always
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root123'
    ports:
      - "5432:5432"

